apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplicationsample-deployment
spec:
  selector:
    matchLabels:
      app: webapplicationsample
  template:
    metadata:
      labels:
        app: webapplicationsample
    spec:
      containers:
      - name: webapplicationsample
        image: maesip/webapplicationsample:v2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: webapplicationsample-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapplicationsample-service
spec:
  type: LoadBalancer
  selector:
    app: webapplicationsample
  ports:
    - port: 8090
      targetPort: 80

          